apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "test4"
  description: "test4"
  annotations:
    github.com/project-slug: cultureamp/mt-test-2
    buildkite.com/project-slug: culture-amp/mt-test-2
spec:
  type: service
  lifecycle: development
  owner: matthewtapper
